#!/usr/bin/env node
/*
 * gen_battlefield_icons.js -- embeds the compact terrain art used by the combat sidebar into a generated
 * window.BATTLEFIELD_ICONS map. Like the action/spell icon generators, this keeps the standalone play_game.html
 * self-contained: the source art stays in ICONS/, while the UI reads data URIs in development and compiled play.
 *
 * Run: node tools/gen_battlefield_icons.js
 *      node tools/gen_battlefield_icons.js --check
 */
const fs = require("fs");
const path = require("path");

const ROOT = path.resolve(__dirname, "..");
const ICONS = path.join(ROOT, "ICONS");
const OUT = path.join(ROOT, "web", "mygame", "battlefield-icons.js");
const checkOnly = process.argv.includes("--check");

const MAP = {
  chokepoint: "Battlefield/Chokepoint.png",
  cover: "Battlefield/Cover.png",
  difficult_terrain: "Battlefield/Difficult_terrain.png",
  high_ground: "Battlefield/High_Ground.png",
  open_ground: "Battlefield/Open_Ground.png"
};
const MIME = { ".png": "image/png", ".webp": "image/webp", ".jpg": "image/jpeg", ".svg": "image/svg+xml" };

let bytes = 0, bad = 0;
const out = {};
for (const id of Object.keys(MAP).sort()) {
  const source = path.join(ICONS, MAP[id]);
  if (!fs.existsSync(source)) { console.warn("  MISSING: " + id + " -> " + MAP[id]); bad++; continue; }
  const mime = MIME[path.extname(source).toLowerCase()];
  out[id] = "data:" + mime + ";base64," + fs.readFileSync(source).toString("base64");
  bytes += fs.statSync(source).size;
}

const body = "/*\n * BATTLEFIELD ICONS -- generated by tools/gen_battlefield_icons.js from the ICONS/Battlefield art library.\n * Do not edit by hand; update MAP in that generator, then rerun it. Used by the combat turn-order cards.\n */\n" +
  "window.BATTLEFIELD_ICONS = " + JSON.stringify(out) + ";\n";

if (checkOnly) {
  const current = fs.existsSync(OUT) ? fs.readFileSync(OUT, "utf8").replace(/\r\n/g, "\n") : "";
  if (current !== body || bad) { console.error("battlefield-icons.js is STALE or incomplete -- re-run node tools/gen_battlefield_icons.js"); process.exit(1); }
  console.log("battlefield-icons.js is up to date (" + Object.keys(out).length + " terrain icons, " + Math.round(bytes / 1024) + " KB of art)");
} else {
  fs.writeFileSync(OUT, body);
  console.log("wrote " + path.relative(ROOT, OUT) + ": " + Object.keys(out).length + " terrain icons, " + Math.round(bytes / 1024) + " KB of art" + (bad ? "; " + bad + " MISSING" : ""));
  if (bad) process.exit(1);
}
