/*
 * INVENTORY PANEL -- one window: the character's equipment slots on the left (a paper doll) and the carried gear on the right as a grid of icons (2026-10-02,
 * redone from the old lists and dropdowns). Reads its catalog from inventory-data.js and live game state from window.stats (the same object the stat sidebar
 * and lorebook read), so it never goes stale; writes go through EquipmentEngine (equipment-panel.js), never directly.
 *
 * Wearing something: drag a bag item onto the slot that takes it, double-click it, or select it and press Equip (the last two work on a touch screen too, where
 * dragging does not). Clicking a slot opens the list of everything that fits it, including "switch back to starting gear", exactly the options the old
 * dropdowns offered. Hovering an item or a slot shows its card. Neck pieces and rings are worn and taken off here too. Two kinds of change are handed to the
 * dossier's ChoiceScript instead of being written here, because they change scores or max HP: a piece with an ability-score bonus (equipViaDossier) and the
 * Hearthstone Talisman's attunement (attuneViaDossier).
 *
 * Every equip control only ever offers the ids EquipmentEngine's catalog actually knows about (from equipment.txt) AND that the player currently has access to --
 * whatever is already equipped (even a class-starting loadout item with no matching Satchel entry), and anything in the Satchel whose `equip.slot` matches. The
 * pictures come from item-icons.js (generated by tools/gen_item_icons.js) through iconFor logic below.
 *
 * Open with the Inventory button or the I key.
 *
 * A Rest bar sits at the top of the bag (see restBadge): it is not a catalog item, and its button opens the dossier's Rest menu (choicescript_stats codex_rest).
 */
(function () {
  "use strict";

  var INV = window.InventoryPanel = window.InventoryPanel || {};

  function truthy(v) { return v === true || v === "true"; }
  function esc(s) {
    return String(s == null ? "" : s)
      .replace(/&/g, "&amp;").replace(/</g, "&lt;")
      .replace(/>/g, "&gt;").replace(/"/g, "&quot;");
  }
  function evalField(v, s) { return typeof v === "function" ? v(s) : v; }

  function data() { return window.INVENTORY || { categories: [], equippedSlots: [], items: [] }; }

  function isOwned(item, s) {
    var o = item.owned;
    if (o === undefined || o === null) return true;
    if (typeof o === "function") return !!o(s);
    return truthy(s[o]);
  }

  // Turns a catalog entry into plain, ready-to-render values for the current game state.
  // Hand-written items name their slot through equip.slot; generated ones carry a ready label (item.slot).
  var SLOT_NAMES = { weapon: "Weapon", armor: "Body armor", shield: "Off hand", head: "Head", cloak: "Cloak", hands: "Hands", waist: "Waist", feet: "Feet", neck: "Neck", ring: "Ring" };
  function resolve(item, s) {
    return {
      id: item.id,
      category: item.category,
      slot: item.slot || (item.equip && SLOT_NAMES[item.equip.slot]) || "",
      traits: evalField(item.traits, s) || "",
      name: evalField(item.name, s),
      description: evalField(item.description, s),
      badge: evalField(item.badge, s) || "",
      use: !!item.use,
      useLabel: evalField(item.useLabel, s) || "Use",
      equip: item.equip || null
    };
  }

  function owned(s) {
    var out = [];
    data().items.forEach(function (item) {
      if (isOwned(item, s)) out.push(resolve(item, s));
    });
    return out;
  }

  /* ---------------------------------------------------------------- equipped slots */

  // Each shape knows how to turn a slot descriptor + live stats into {desc, meta, empty}.
  // "empty" governs the dimmed/placeholder styling for a slot with nothing worn.
  var EMPTY_DESCS = { "bare head": 1, "none": 1, "bare finger": 1, "bare throat": 1, "bare feet": 1, "bare hands": 1 };   // compared in lower case: the game writes "Bare Throat"

  // What a worn piece does (weather cuts, ability-score bonus): the text comes from equipment.txt garment_traits through
  // window.GARMENT_HINTS (generated), so the card can never disagree with the game. The attuned Hearthstone is the one
  // worn piece that is not in that table.
  var WORN_ID = { armor: "equipped_armor_id", head: "equipped_head_id", cloak: "equipped_cloak_id", hands: "equipped_hands_id",
    waist: "equipped_waist_id", feet: "equipped_feet_id", neck: "equipped_neck_id" };
  var PLAIN_WORN = { head: 1, cloak: 1, hands: 1, waist: 1, feet: 1, neck: 1 };
  function wornTraits(bucket, s) {
    var id = WORN_ID[bucket] ? s[WORN_ID[bucket]] : "";
    if (!id) return "";
    if (id === "hearthstone_talisman") return "+1 CON, attuned";
    return (window.GARMENT_HINTS || {})[id] || "";
  }

  function renderSlotValue(slot, s) {
    var desc = slot.desc ? (s[slot.desc] == null ? "" : String(s[slot.desc])) : "";
    var empty = !!EMPTY_DESCS[desc.toLowerCase()];
    var meta = "";
    if (slot.shape === "weapon") {
      var dmg = slot.dmg ? s[slot.dmg] : "";
      if (dmg && dmg !== "none") meta = String(dmg);
    } else if (slot.shape === "armor") {
      var ac = slot.ac ? s[slot.ac] : null;
      if (ac !== null && ac !== undefined && ac !== "") meta = "AC " + ac;
    } else if (slot.shape === "headwear") {
      if (truthy(s[slot.isArmor]) && Number(s[slot.ac]) > 0) meta = "+" + s[slot.ac] + " AC";
    } else if (slot.shape === "shield") {
      var hasShield = truthy(s.has_shield);
      var shieldOn = truthy(s.shield_equipped);
      desc = hasShield ? "Oak Shield" : "No shield carried";
      empty = !hasShield || !shieldOn;
      meta = hasShield ? (shieldOn ? "Equipped, +2 AC" : "Stowed") : "";
    }
    // A worn piece with no weather cut or score bonus says so, so a plain slot reads as a choice, not as missing data.
    var traits = wornTraits(slot.bucket, s), noBonus = false;
    if (!traits && !meta && !empty && PLAIN_WORN[slot.bucket]) { traits = "No bonuses"; noBonus = true; }
    return { desc: desc, meta: meta, empty: empty, traits: traits, noBonus: noBonus };
  }

  // Every catalog id for this bucket that the player currently owns (via a Satchel
  // item's `equip.slot`), regardless of category filters -- the swap dropdown always
  // offers every eligible owned item, independent of whichever chip is selected below.
  function ownedIdsForBucket(bucket, s) {
    var ids = [];
    data().items.forEach(function (item) {
      if (item.equip && item.equip.slot === bucket && item.equip.id && isOwned(item, s)) {
        ids.push(item.equip.id);
      }
    });
    return ids;
  }

  // Builds the <option> list for one id-based slot: whatever's currently equipped
  // (even an unowned class-starting choice, so the dropdown never opens on a value
  // that isn't one of its own options) + this slot's `always` id(s) (the menu's own
  // "switch back to starting/origin-default" option) + every owned alternative.
  // Deliberately never offers "none"/unequip -- see inventory-data.js's header comment
  // on `swappable` for why that's a narrative-only state in the real menu, not
  // something a dropdown here should be able to reach.
  function buildSlotOptions(slot, currentId, s) {
    var ids = [];
    function add(id) { if (id && ids.indexOf(id) === -1) ids.push(id); }
    add(currentId);
    if (slot.always) evalField(slot.always, s).forEach(add);
    ownedIdsForBucket(slot.bucket, s).forEach(add);
    return ids.map(function (id) {
      return { id: id, label: window.EquipmentEngine.describeOption(slot.bucket, id) };
    });
  }

  /* ----------------------------------------------------------------------- icons */

  // Which picture an item gets (2026-10-02). Keys are WHAT AN ITEM IS, not which item: many items share one, and tools/gen_item_icons.js maps each key to a
  // file in ICONS/Item and writes window.ITEM_ICONS. An item with no entry here falls back by its slot or category, and a key with no art falls back to "misc",
  // so a new item always shows something. Replace a stand-in by editing MAP in that generator, not here.
  var ID_ICON = {
    timber_axe: "w_battleaxe", stiletto: "w_dagger", iron_crowbar: "tool", torvald_iron_sallet: "h_helm", torvald_hide_cap: "h_cap",
    brigandine: "a_brig", chain_jack: "a_chain", plate_harness: "a_plate", court_coat: "a_coat", shield: "shield", toll_seal_ring: "signet",
    warming_liniment: "salve", clear_head_draught: "elixir", althea_phial: "potion", linen_bandage: "bandage", lye_soap: "soap",
    hemp_rope: "rope", pitch_torch: "torch", lamp_oil: "oil", hooded_lantern: "lantern", tool_kit: "toolkit", tinderbox: "tinder", chalk_sticks: "chalk",
    wool_blanket: "blanket", waxed_oilcloth: "cloth", lockpick_set: "lockpicks", padlock: "key", door_bolt: "tool", iron_manacles: "tool",
    broadcloth_cloak: "cloak", storm_cape: "cloak", winter_cloak: "cloak", summer_duster: "cloak", felt_hat: "h_hat", fur_cap: "h_cap",
    lined_gloves: "gloves", scholar_gloves: "gloves", masters_gloves: "gloves", waxed_boots: "boots", winter_boots: "boots", dancing_slippers: "slippers",
    wool_muffler: "neck", silk_neckcloth: "neck", scrap_steel: "scrap", frog_slime: "frog_slime", centipede_gland: "gland", viper_venom: "venom", grave_ichor: "ichor",
    talia_oiled_cloak: "cloak", rorik_grip_wraps: "gloves", rorik_campaign_belt: "belt", talia_deck_boots: "boots", brant_iron_heel_boots: "boots",
    althea_votive_ring: "ring", night_eye_ring: "ring", hearthstone_talisman: "stone", odessa_salve: "salve", fish_cache: "fish", kestrel_dispatch: "letter", ysolde_requisition: "letter",
    vanguard_grease_chit: "note", customs_vellum: "ledger", waterproof_gear: "jug", talia_provisions: "food", rotten_rib_splinter: "splinter",
    diverted_timber_waybill: "note", silt_gate_payout_slip: "note", hall_insignia: "signet", letter_of_credit: "letter"
  };
  var BUCKET_ICON = { weapon: "w_generic", sidearm: "w_generic", armor: "a_generic", shield: "shield", head: "h_cap", cloak: "cloak", hands: "gloves", waist: "belt", feet: "boots", neck: "neck", ring: "ring" };
  var CATEGORY_ICON = { weapons: "w_generic", apparel: "a_generic", accessories: "ring", provisions: "sack", documents: "note", consumables: "potion" };

  // A weapon's picture from its own name ("Twin Daggers", "Hooked Broadaxe", "Ash-Wood Spear").
  function weaponIcon(desc) {
    var d = String(desc || "").toLowerCase();
    if (/dagger|stiletto|knife|dirk/.test(d)) return "w_dagger";
    if (/crossbow/.test(d)) return "w_xbow";
    if (/\bbow\b|shortbow|longbow/.test(d)) return "w_bow";
    if (/broadaxe|greataxe|great axe/.test(d)) return "w_greataxe";
    if (/axe|hatchet/.test(d)) return "w_axe";
    if (/spear|pike|lance/.test(d)) return "w_spear";
    if (/staff/.test(d)) return "w_staff";
    if (/hammer|maul/.test(d)) return "w_hammer";
    if (/club|cudgel/.test(d)) return "w_club";
    if (/mace/.test(d)) return "w_mace";
    if (/sword|falchion|blade|saber|sabre|scimitar|rapier/.test(d)) return "w_sword";
    return "w_generic";
  }
  function headIcon(desc) {
    var d = String(desc || "").toLowerCase();
    if (/hat/.test(d)) return "h_hat";
    if (/helm|sallet|skullcap|plate/.test(d)) return "h_helm";
    return "h_cap";
  }
  function armorIcon(s) {
    var type = String(s.armor_type || ""), d = String(s.armor_desc || "").toLowerCase();
    if (/court/.test(d)) return "a_coat";
    if (type === "cloth") return "a_cloth";
    if (type === "leather") return "a_leather";
    if (type === "chain_jack" || /scale|chain/.test(d)) return "a_chain";
    if (type === "plate_harness") return "a_plate";
    if (type === "brigandine" || type === "buff_coat") return "a_brig";
    return "a_generic";
  }
  // The picture on one doll slot: the worn piece's own icon, or a dim stand-in for the kind of slot when nothing is worn.
  function slotIconKey(bucket, ringSlot, s) {
    var EQ = window.EquipmentEngine, id = "";
    if (EQ && bucket !== "shield" && bucket !== "sidearm") { try { id = EQ.getEquippedId(bucket, ringSlot) || ""; } catch (e) { id = ""; } }
    if (id && ID_ICON[id]) return ID_ICON[id];
    if (bucket === "weapon") return weaponIcon(s.weapon_desc);
    if (bucket === "sidearm") return weaponIcon(s.sidearm_desc);
    if (bucket === "armor") return armorIcon(s);
    if (bucket === "head") return headIcon(s.head_desc);
    if (bucket === "feet" && /slipper/i.test(String(s.feet_desc || ""))) return "slippers";
    return BUCKET_ICON[bucket] || "misc";
  }
  function itemIconKey(r) {
    if (ID_ICON[r.id]) return ID_ICON[r.id];
    var slot = r.equip && r.equip.slot;
    if (slot === "weapon") return weaponIcon(r.name);
    if (slot === "head") return headIcon(r.name);
    if (slot && BUCKET_ICON[slot]) return BUCKET_ICON[slot];
    return CATEGORY_ICON[r.category] || "misc";
  }
  function iconSrc(key) {
    var all = window.ITEM_ICONS || {};
    return all[key] || all.misc || "";
  }
  function iconImg(key) { var src = iconSrc(key); return src ? '<img class="inv-ico" alt="" draggable="false" src="' + src + '">' : '<span class="inv-ico inv-ico-none"></span>'; }

  // Stackable items put their count in the name ("Oak Shield x2" or "Scrap Steel (5)"); the tile shows it as a badge instead.
  function splitCount(name) {
    var m = /^(.*?)\s*(?:×\s*(\d+)|\((\d+)\))\s*$/.exec(String(name || ""));
    if (m) return { name: m[1], count: Number(m[2] || m[3]) };
    return { name: String(name || ""), count: 1 };
  }

  /* ---------------------------------------------------------------------- DOM */

  if (typeof document === "undefined") return; // node tests stop here (mirrors lorebook.js)

  var dlg, elDoll, elBag, elTip;
  var view = { category: "", sel: null, drag: null, pop: null, note: "" };

  function statsNow() { return window.stats || {}; }

  // The doll: two columns of slots either side of the figure, and the weapons along the bottom. [bucket, ringSlot, column, row]
  var DOLL_SLOTS = [
    ["head", "", 1, 1], ["cloak", "", 1, 2], ["armor", "", 1, 3], ["waist", "", 1, 4], ["feet", "", 1, 5],
    ["neck", "", 3, 1], ["hands", "", 3, 2], ["shield", "", 3, 3], ["ring", "1", 3, 4], ["ring", "2", 3, 5]
  ];

  function slotDesc(bucket, ringSlot) {
    var slots = data().equippedSlots || [];
    for (var i = 0; i < slots.length; i++) {
      if (slots[i].bucket === bucket && (slots[i].ringSlot || "") === (ringSlot || "")) return slots[i];
    }
    return null;
  }

  function build() {
    if (dlg) return;
    dlg = document.createElement("dialog");
    dlg.id = "inventory";
    dlg.setAttribute("aria-label", "Inventory");
    dlg.innerHTML =
      '<div class="inv-head">' +
        "<h2>Inventory</h2>" +
        '<span class="inv-count"></span><span class="inv-spacer"></span>' +
        '<button type="button" class="inv-close" data-act="close" aria-label="Close inventory">×</button>' +
      "</div>" +
      '<div class="inv-main">' +
        '<section class="inv-doll" aria-label="Equipment"></section>' +
        '<section class="inv-bag" aria-label="Carried gear"></section>' +
      "</div>" +
      '<div class="inv-tip" id="invTip" role="tooltip"></div>';
    document.body.appendChild(dlg);

    elDoll = dlg.querySelector(".inv-doll");
    elBag = dlg.querySelector(".inv-bag");
    elTip = dlg.querySelector("#invTip");

    dlg.addEventListener("click", onClick);
    dlg.addEventListener("dblclick", onDblClick);
    dlg.addEventListener("mouseover", onOver);
    dlg.addEventListener("mouseleave", hideTip);
    dlg.addEventListener("focusin", onOver);
    dlg.addEventListener("dragstart", onDragStart);
    dlg.addEventListener("dragend", onDragEnd);
    dlg.addEventListener("dragover", onDragOver);
    dlg.addEventListener("drop", onDrop);
    // Stop typing/keys from leaking to the game's own global hotkeys (J/K/Q/W/1-9) while this panel is open, but still handle I here ourselves:
    // a listener on document would never see it, since this one already stopped its propagation. Escape also closes a slot's option list first.
    dlg.addEventListener("keydown", function (ev) {
      ev.stopPropagation();
      if (isTextTarget(ev.target)) return;
      if (ev.key === "Escape" && view.pop) { ev.preventDefault(); view.pop = null; render(); return; }
      if ((ev.key === "i" || ev.key === "I") && !ev.ctrlKey && !ev.metaKey && !ev.altKey) {
        ev.preventDefault();
        close();
      }
    });
    dlg.addEventListener("mousedown", function (ev) { if (ev.target === dlg) close(); });
  }

  function categoryLabel(id) {
    var cats = data().categories;
    for (var i = 0; i < cats.length; i++) if (cats[i].id === id) return cats[i].label;
    return id;
  }

  /* ---------------------------------------------------------------- what can go where */

  function findOwned(id) {
    var list = owned(statsNow());
    for (var i = 0; i < list.length; i++) if (list[i].id === id) return list[i];
    return null;
  }
  // Does this bag item belong on that doll slot? Only items that carry an equip.slot ever do; a weapon goes on the Primary slot (the sidearm is changed
  // with the swap button) and a ring goes on either ring slot.
  function accepts(r, bucket) { return !!(r && r.equip && r.equip.slot === bucket); }
  function slotSwappable(bucket, ringSlot) { var d = slotDesc(bucket, ringSlot); return !!(d && d.swappable); }

  function note(msg) { view.note = msg || ""; }

  // The single path that puts something on: the same EquipmentEngine calls the old dropdowns made, with the same hand-off to the dossier for
  // pieces that change an ability score (the scores, max HP and AC are re-derived by ChoiceScript there).
  function equipTo(bucket, id, ringSlot) {
    var EQ = window.EquipmentEngine;
    if (!EQ) return;
    if (!slotSwappable(bucket, ringSlot)) { note("This slot is changed from the dossier's Equipment menu."); render(); return; }
    if (bucket === "shield") {
      if (statsNow().weapon_hands === "two_handed") { note("Your weapon needs both hands, so there is no hand free for a shield."); render(); return; }
      EQ.equipItem("shield");
      view.pop = null; view.sel = null; note(""); render();
      return;
    }
    if (bucket === "neck" && id === "hearthstone_talisman") { attuneViaDossier("attune"); return; }
    var current = EQ.getEquippedId(bucket, ringSlot);
    if (!ringSlot && (hasStatBonus(bucket, id) || hasStatBonus(bucket, current))) { equipViaDossier(bucket, id); return; }
    // one ring cannot sit on two fingers: putting it on one hand takes it off the other
    if (bucket === "ring" && id !== "none") {
      var other = ringSlot === "1" ? "2" : "1";
      if (EQ.getEquippedId("ring", other) === id) EQ.equipItem("ring", "none", other);
    }
    EQ.equipItem(bucket, id, ringSlot);
    view.pop = null; view.sel = null; note(""); render();
  }

  // Which finger a ring goes on when the player did not pick one: the one it is already on, else the first bare one, else the first.
  function ringTarget(id) {
    var EQ = window.EquipmentEngine;
    if (EQ.getEquippedId("ring", "1") === id) return "1";
    if (EQ.getEquippedId("ring", "2") === id) return "2";
    if (EQ.getEquippedId("ring", "1") === "none") return "1";
    if (EQ.getEquippedId("ring", "2") === "none") return "2";
    return "1";
  }

  function equipSelected(bucket, ringSlot) {
    var r = findOwned(view.sel);
    if (!r || !accepts(r, bucket)) return;
    equipTo(bucket, r.equip.id, ringSlot);
  }

  /* ---------------------------------------------------------------- the doll */

  function slotTileHtml(bucket, ringSlot, col, row) {
    var s = statsNow(), d = slotDesc(bucket, ringSlot);
    if (!d) return "";
    var v = renderSlotValue(d, s);
    var picked = view.drag || view.sel, r = picked ? findOwned(picked) : null;
    var ok = accepts(r, bucket);
    var buffed = !!v.meta || (!!v.traits && !v.noBonus);
    var cls = "inv-tile inv-slot" + (v.empty ? " inv-slot-empty" : "") + (buffed ? " inv-slot-buffed" : "") + (ok ? " inv-accepts" : "") +
      (view.pop && view.pop.bucket === bucket && (view.pop.ring || "") === (ringSlot || "") ? " inv-sel" : "");
    var pos = col ? ' style="grid-column:' + col + ";grid-row:" + row + '"' : "";
    return '<button type="button" class="' + cls + '" data-slot="' + esc(bucket) + '"' + (ringSlot ? ' data-ring="' + esc(ringSlot) + '"' : "") + pos +
      ' aria-label="' + esc(d.label + ": " + (v.empty ? "empty" : v.desc)) + '">' + iconImg(slotIconKey(bucket, ringSlot, s)) + "</button>";
  }

  function popHtml() {
    if (!view.pop) return "";
    var s = statsNow(), EQ = window.EquipmentEngine, d = slotDesc(view.pop.bucket, view.pop.ring);
    if (!d || !EQ) return "";
    var html = '<div class="inv-pop" style="left:0;top:0;visibility:hidden"><div class="inv-pop-title">' + esc(d.label) + "</div>";
    if (d.bucket === "shield") {
      if (!truthy(s.has_shield)) html += '<div class="inv-pop-note">No shield carried.</div>';
      else html += '<button type="button" class="inv-pop-opt" data-pop-shield>' + (truthy(s.shield_equipped) ? "Stow the shield" : "Take up the shield") + "</button>";
    } else if (d.bucket === "sidearm") {
      html += '<button type="button" class="inv-pop-opt" data-swap-sidearm>⇄ Swap weapon and sidearm</button>';
    } else if (!d.swappable) {
      html += '<div class="inv-pop-note">Changed from the dossier’s Equipment menu.</div>';
    } else if (d.bucket === "neck" && truthy(s.hearthstone_attuned)) {
      html += '<div class="inv-pop-note">Torvald’s Hearthstone Talisman is worn, attuned (+1 CON).</div>' +
        '<button type="button" class="inv-pop-opt" data-attune="break">Break the attunement</button>';
    } else {
      var currentId = EQ.getEquippedId(d.bucket, d.ringSlot);
      var options = buildSlotOptions(d, currentId, s);
      if (options.length < 2) html += '<div class="inv-pop-note">Nothing else to wear here.</div>';
      options.forEach(function (opt) {
        html += '<button type="button" class="inv-pop-opt' + (opt.id === currentId ? " inv-pop-cur" : "") + '" data-pop-id="' + esc(opt.id) + '"' + (opt.id === currentId ? " disabled" : "") + ">" +
          esc(opt.label) + (opt.id === currentId ? " (worn)" : (opt.id === "hearthstone_talisman" ? " (attune, +1 CON)" : "")) + "</button>";
      });
    }
    return html + "</div>";
  }

  function renderDoll(s) {
    var html = '<div class="inv-fig"><div class="inv-figart"></div>';
    DOLL_SLOTS.forEach(function (d) { html += slotTileHtml(d[0], d[1], d[2], d[3]); });
    html += "</div>";
    html += '<div class="inv-weapons">' + slotTileHtml("weapon", "", 0, 0) + slotTileHtml("sidearm", "", 0, 0) + "</div>";
    var hasSidearm = s.equipped_sidearm_id && s.equipped_sidearm_id !== "none";
    if (hasSidearm && window.EquipmentEngine) html += '<button type="button" class="inv-swap-sidearm" data-swap-sidearm>⇄ Swap Weapon &amp; Sidearm</button>';
    html += '<div class="inv-vitals"><span>AC <b>' + esc(s.armor_class) + '</b></span><span>HP <b>' + esc(s.hp_current) + "/" + esc(s.hp_max) + '</b></span><span>Proficiency <b>+' + esc(s.prof_bonus) + "</b></span></div>";
    elDoll.innerHTML = html + popHtml();
  }

  /* ---------------------------------------------------------------- the bag */

  // The Rest card: not an item you own, so it is not in the catalog and not counted. Its button opens the dossier's Rest menu (choicescript_stats
  // codex_rest), the same way Use opens the satchel. The badge shows the one number a short rest is for.
  function restBadge(s) {
    if (s.character_class === "fighter") {
      return "Second Wind " + s.fighter_second_wind_uses + "/" + s.fighter_second_wind_max +
        (Number(s.fighter_action_surge_max) > 0 ? " · Action Surge " + s.fighter_action_surge_uses + "/" + s.fighter_action_surge_max : "");
    }
    if (s.character_class === "warlock") return "Pact slot " + s.warlock_spell_slots + "/" + s.warlock_spell_slots_max;
    return "";
  }

  function purseText(s) {
    var parts = [];
    if (Number(s.gold)) parts.push(s.gold + " Gold");
    if (Number(s.silver)) parts.push(s.silver + " Silver");
    if (Number(s.copper) || !parts.length) parts.push((Number(s.copper) || 0) + " Copper");
    return parts.join(", ");
  }

  var MIN_CELLS = 30, COLS = 6;

  function renderBag(s) {
    var current = owned(s);
    dlg.querySelector(".inv-count").textContent = current.length + (current.length === 1 ? " item carried" : " items carried");

    var counts = {};
    current.forEach(function (r) { counts[r.category] = (counts[r.category] || 0) + 1; });
    var html = "";
    var trading = !!(window.TradePanel && window.TradePanel.isActive());
    if (trading) {
      html += '<div class="inv-tradebar"><span class="inv-tradebar-title">Trading at ' + esc(window.TradePanel.title()) + '</span>' +
        '<button type="button" data-act="trade">Open trade panel</button></div>';
    }
    var badge = restBadge(s);
    html += '<div class="inv-restbar"><span class="inv-rest-name">Rest</span>' + (badge ? '<span class="inv-item-badge">' + esc(badge) + "</span>" : "") +
      '<span class="inv-spacer"></span><button type="button" class="inv-use" data-rest' + (canUse() ? "" : " disabled") + ">Rest…</button></div>";

    html += '<div class="inv-chips"><button type="button" class="inv-chip" data-cat="" aria-pressed="' + (!view.category) + '">All<small>' + current.length + "</small></button>";
    data().categories.forEach(function (c) {
      if (!counts[c.id]) return;
      html += '<button type="button" class="inv-chip" data-cat="' + esc(c.id) + '" aria-pressed="' + (view.category === c.id) + '">' + esc(c.label) + "<small>" + counts[c.id] + "</small></button>";
    });
    html += "</div>";

    var shown = view.category ? current.filter(function (r) { return r.category === view.category; }) : current;
    html += '<div class="inv-grid">';
    shown.forEach(function (r) {
      var c = splitCount(r.name);
      var on = /^equipped/i.test(r.badge || "");
      html += '<button type="button" class="inv-tile inv-bagitem' + (view.sel === r.id ? " inv-sel" : "") + (on ? " inv-on" : "") + '" data-item="' + esc(r.id) + '"' +
        (r.equip ? ' draggable="true"' : "") + ' aria-label="' + esc(c.name) + '">' + iconImg(itemIconKey(r)) +
        (c.count > 1 ? '<span class="inv-cnt">' + c.count + "</span>" : "") + (on ? '<span class="inv-eq" aria-hidden="true"></span>' : "") + "</button>";
    });
    var cells = Math.max(MIN_CELLS, Math.ceil(shown.length / COLS) * COLS);
    for (var i = shown.length; i < cells; i++) html += '<span class="inv-tile inv-blank" aria-hidden="true"></span>';
    html += "</div>";

    // the selected item's details and its actions, under the grid: the touch-friendly way to do what hovering and dragging do on a desktop
    var sel = view.sel ? findOwned(view.sel) : null;
    html += '<div class="inv-detail">';
    if (view.note) html += '<div class="inv-note inv-note-warn">' + esc(view.note) + "</div>";
    if (sel) {
      var sc = splitCount(sel.name);
      html += '<div class="inv-detail-main"><div class="inv-detail-name">' + esc(sc.name) + (sel.slot ? '<span class="inv-item-slot">' + esc(sel.slot) + "</span>" : "") +
        (sel.badge ? '<span class="inv-item-badge">' + esc(sel.badge) + "</span>" : "") + "</div>" +
        (sel.traits ? '<div class="inv-item-traits">' + esc(sel.traits) + "</div>" : "") +
        (sel.description ? '<div class="inv-item-desc">' + esc(sel.description) + "</div>" : "") + "</div>" +
        '<div class="inv-detail-acts">' +
        (sel.equip && sel.equip.attune ? '<button type="button" class="inv-use" data-attune="' + (truthy(s.hearthstone_attuned) ? "break" : "attune") + '">' + (truthy(s.hearthstone_attuned) ? "Break attunement" : "Attune") + "</button>"
          : (sel.equip ? '<button type="button" class="inv-use" data-equip-sel>Equip</button>' : "")) +
        (sel.use ? '<button type="button" class="inv-use" data-use="' + esc(sel.id) + '"' + (canUse() ? "" : " disabled") + ">" + esc(sel.useLabel) + "</button>" : "") +
        "</div>";
    } else if (view.note) {
      /* the notice above is all there is to say */
    } else if (!current.length) {
      html += '<div class="inv-note">Your satchel holds only dry trail rations, flint and steel, and basic road gear.</div>';
    } else {
      html += '<div class="inv-note">Drag a piece onto the figure to wear it, or select it and press Equip. Click a slot to see what else fits.</div>';
    }
    html += '<div class="inv-purse" title="Coin on you">' + esc(purseText(s)) + "</div></div>";
    elBag.innerHTML = html;
  }

  function render() {
    var s = statsNow();
    hideTip();
    renderDoll(s);
    renderBag(s);
    placePop();
  }

  /* ---------------------------------------------------------------- hover cards */

  function hideTip() { if (elTip) elTip.className = "inv-tip"; }
  function tipHtmlForItem(r) {
    var c = splitCount(r.name);
    return '<div class="bt-name">' + esc(c.name) + (c.count > 1 ? " ×" + c.count : "") + "</div>" +
      (r.slot || r.badge ? '<div class="bt-kind">' + esc([r.slot, r.badge].filter(Boolean).join(" · ")) + "</div>" : "") +
      (r.traits ? '<div class="bt-meta">' + esc(r.traits) + "</div>" : "") +
      (r.description ? '<div class="bt-text">' + esc(r.description) + "</div>" : "") +
      (r.equip ? '<div class="bt-hint">Drag to a slot, or double-click to equip</div>' : (r.use ? '<div class="bt-hint">Double-click to use</div>' : ""));
  }
  function tipHtmlForSlot(bucket, ringSlot) {
    var d = slotDesc(bucket, ringSlot), s = statsNow();
    if (!d) return "";
    var v = renderSlotValue(d, s);
    return '<div class="bt-name">' + esc(v.empty ? "Nothing worn" : v.desc) + "</div>" +
      '<div class="bt-kind">' + esc(d.label) + "</div>" +
      (v.meta ? '<div class="bt-meta">' + esc(v.meta) + "</div>" : "") +
      (v.traits ? '<div class="bt-meta' + (v.noBonus ? " bt-dim" : "") + '">' + esc(v.traits) + "</div>" : "") +
      '<div class="bt-hint">' + (d.swappable || d.bucket === "sidearm" ? "Click to change what is worn here" : "Changed from the dossier’s Equipment menu") + "</div>";
  }
  function showTip(el, html) {
    if (!html) { hideTip(); return; }
    elTip.innerHTML = html;
    elTip.className = "inv-tip on";
    // Positioned inside the dialog in CSS pixels, which the screen-fit zoom scales (index.html, window.UI_ZOOM): measure in viewport pixels, divide by the zoom.
    var z = window.UI_ZOOM || 1;
    var d = dlg.getBoundingClientRect(), r = el.getBoundingClientRect(), t = elTip.getBoundingClientRect();
    // The card lives inside the dialog, and everything inside is clipped to its PADDING box (inside the bronze frame, which is a border of a few CSS pixels), so
    // the card is kept within that box, not the outer edge: clamped there, and measured from there, since an absolutely positioned child's origin is the padding box.
    var cs = window.getComputedStyle(dlg);
    var bl = parseFloat(cs.borderLeftWidth) || 0, br = parseFloat(cs.borderRightWidth) || 0, bt = parseFloat(cs.borderTopWidth) || 0, bb = parseFloat(cs.borderBottomWidth) || 0;
    var padL = d.left + bl * z, padR = d.right - br * z, padT = d.top + bt * z, padB = d.bottom - bb * z, gap = 6 * z;
    var left, top;
    if (el.parentNode && el.parentNode.classList && el.parentNode.classList.contains("inv-fig")) {
      // a slot in one of the side columns: the card goes beside it, over the figure, so it never hides the slot above or below
      var onLeft = (r.left + r.width / 2) < (d.left + d.width / 2);
      left = onLeft ? r.right + 10 * z : r.left - t.width - 10 * z;
      top = r.top + r.height / 2 - t.height / 2;
    } else {
      left = r.left + r.width / 2 - t.width / 2;
      top = r.top - t.height - 8 * z;
      if (top < padT + gap) top = r.bottom + 8 * z;
    }
    left = Math.min(Math.max(padL + gap, left), padR - t.width - gap);
    top = Math.max(padT + gap, Math.min(top, padB - t.height - gap));
    elTip.style.left = ((left - padL) / z) + "px";
    elTip.style.top = ((top - padT) / z) + "px";
  }
  function onOver(ev) {
    var t = ev.target && ev.target.closest ? ev.target.closest("[data-item], [data-slot]") : null;
    if (!t || view.drag) { if (!t) hideTip(); return; }
    if (t.hasAttribute("data-item")) showTip(t, tipHtmlForItem(findOwned(t.getAttribute("data-item")) || {}));
    else showTip(t, tipHtmlForSlot(t.getAttribute("data-slot"), t.getAttribute("data-ring") || ""));
  }

  /* ---------------------------------------------------------------- drag and drop */

  function onDragStart(ev) {
    var t = ev.target && ev.target.closest ? ev.target.closest("[data-item]") : null;
    if (!t || !findOwned(t.getAttribute("data-item"))) return;
    view.drag = t.getAttribute("data-item");
    try { ev.dataTransfer.setData("text/plain", view.drag); ev.dataTransfer.effectAllowed = "move"; } catch (e) { /* some browsers refuse; the drop reads view.drag */ }
    hideTip();
    // mark the slots that take it, without rebuilding the DOM mid-drag (that would cancel the drag)
    var r = findOwned(view.drag);
    Array.prototype.forEach.call(dlg.querySelectorAll("[data-slot]"), function (el) { if (accepts(r, el.getAttribute("data-slot"))) el.classList.add("inv-accepts"); });
  }
  function onDragEnd() {
    view.drag = null;
    Array.prototype.forEach.call(dlg.querySelectorAll(".inv-accepts, .inv-over"), function (el) { el.classList.remove("inv-accepts", "inv-over"); });
  }
  function onDragOver(ev) {
    var t = ev.target && ev.target.closest ? ev.target.closest("[data-slot]") : null;
    Array.prototype.forEach.call(dlg.querySelectorAll(".inv-over"), function (el) { if (el !== t) el.classList.remove("inv-over"); });
    if (!t || !view.drag) return;
    if (accepts(findOwned(view.drag), t.getAttribute("data-slot"))) { ev.preventDefault(); t.classList.add("inv-over"); }
  }
  function onDrop(ev) {
    var t = ev.target && ev.target.closest ? ev.target.closest("[data-slot]") : null;
    var id = view.drag;
    if (!t || !id) return;
    ev.preventDefault();
    var r = findOwned(id), bucket = t.getAttribute("data-slot");
    view.drag = null;
    if (accepts(r, bucket)) equipTo(bucket, r.equip.id, t.getAttribute("data-ring") || undefined);
    else render();
  }

  // Consumables are used through the game's own dossier (real ChoiceScript: equipment.txt use_consumable is the only
  // place an effect is written, so nothing is mirrored here). The Use button drops straight onto the result page
  // (choicescript_stats codex_use_do); from there the satchel menu and the dossier are one tap away. Not offered
  // mid-fight (the fight has its own item option) or while the dossier is already open. "Open" is the running scene being the stats
  // scene, not the Show Stats button's data-return marker: closing the dossier from its own menu leaves that marker set.
  function canUse() {
    var sc = statsNow().scene;
    if (sc && sc.secondaryMode === "stats") return false;
    return !truthy(statsNow().combat_engaged) && typeof window.Scene === "function" && typeof window.clearScreen === "function" && !!window.nav;
  }
  function useItem(id) {
    if (!canUse()) return;
    statsNow().use_item_id = id;
    close();
    var scene = new window.Scene("choicescript_stats", window.stats, window.nav, { secondaryMode: "stats", saveSlot: "temp" });
    scene.targetLabel = { label: "codex_use_do", origin: "url", originLine: 0 };
    window.clearScreen(function () {
      if (typeof window.setButtonTitles === "function") window.setButtonTitles();
      scene.execute();
    });
  }

  function openRest() {
    if (!canUse()) return;
    close();
    var scene = new window.Scene("choicescript_stats", window.stats, window.nav, { secondaryMode: "stats", saveSlot: "temp" });
    scene.targetLabel = { label: "codex_rest", origin: "url", originLine: 0 };
    window.clearScreen(function () {
      if (typeof window.setButtonTitles === "function") window.setButtonTitles();
      scene.execute();
    });
  }

  // A piece with an ability-score bonus (item.statBonus, from the catalog's traits) cannot be swapped here: the scores,
  // max HP and AC are re-derived by ChoiceScript (startup.txt recalculate_equipment_bonuses), so the swap is handed to
  // the dossier exactly like the Use button. Applies when the piece going on OR coming off carries a bonus.
  function hasStatBonus(bucket, id) {
    return data().items.some(function (item) {
      return item.statBonus && item.equip && item.equip.slot === bucket && item.equip.id === id;
    });
  }
  // Attuning the Hearthstone changes CON and max HP, so ChoiceScript does it (choicescript_stats codex_attune_do); not available during a fight, like any hand-off.
  function attuneViaDossier(action) {
    if (!canUse()) { note("Attunement is changed from the dossier, and not in the middle of a fight."); render(); return; }
    statsNow().attune_action = action;
    close();
    var scene = new window.Scene("choicescript_stats", window.stats, window.nav, { secondaryMode: "stats", saveSlot: "temp" });
    scene.targetLabel = { label: "codex_attune_do", origin: "url", originLine: 0 };
    window.clearScreen(function () {
      if (typeof window.setButtonTitles === "function") window.setButtonTitles();
      scene.execute();
    });
  }
  function equipViaDossier(bucket, id) {
    if (!canUse()) { note("That piece changes an ability score, so it is put on from the dossier, and not in the middle of a fight."); render(); return; }
    var st = statsNow();
    st.equip_slot = bucket;
    st.equip_item_id = id;
    close();
    var scene = new window.Scene("choicescript_stats", window.stats, window.nav, { secondaryMode: "stats", saveSlot: "temp" });
    scene.targetLabel = { label: "codex_equip_do", origin: "url", originLine: 0 };
    window.clearScreen(function () {
      if (typeof window.setButtonTitles === "function") window.setButtonTitles();
      scene.execute();
    });
  }

  // Where the option list for a slot sits: just under the tile, or above it when there is no room below, kept inside the doll column. Measured in viewport
  // pixels and set in CSS pixels (the screen-fit zoom, window.UI_ZOOM), the same rule the hover cards follow.
  function placePop() {
    var pop = elDoll.querySelector(".inv-pop");
    if (!pop || !view.pop || !view.pop.anchor) return;
    var z = window.UI_ZOOM || 1, a = view.pop.anchor, dr = elDoll.getBoundingClientRect(), pr = pop.getBoundingClientRect();
    var left = Math.min(Math.max(dr.left + 4, a.left + a.width / 2 - pr.width / 2), dr.right - pr.width - 4);
    var top = a.bottom + 6;
    if (top + pr.height > dr.bottom - 4) top = a.top - pr.height - 6;
    pop.style.left = ((left - dr.left) / z) + "px";
    pop.style.top = ((top - dr.top) / z) + "px";
    pop.style.visibility = "visible";
  }

  function quickAct(id) {
    var r = findOwned(id);
    if (!r) return;
    if (r.equip) {
      var bucket = r.equip.slot;
      equipTo(bucket, r.equip.id, bucket === "ring" ? ringTarget(r.equip.id) : undefined);
    } else if (r.use) {
      useItem(r.id);
    }
  }

  function onClick(ev) {
    var t = ev.target && ev.target.closest ? ev.target.closest("[data-act], [data-cat], [data-item], [data-slot], [data-pop-id], [data-pop-shield], [data-attune], [data-swap-sidearm], [data-equip-sel], [data-use], [data-rest]") : null;
    if (!t || !dlg.contains(t)) {
      if (view.pop) { view.pop = null; render(); }   // a click on empty space puts the option list away
      return;
    }
    var act = t.getAttribute("data-act");
    if (act === "close") return close();
    if (act === "trade") {
      // The trade panel (trade.js) sits over the shop menus; from here it is one tap away.
      close();
      if (window.TradePanel) window.TradePanel.open();
      return;
    }
    if (t.hasAttribute("data-rest")) { if (!t.disabled) openRest(); return; }
    if (t.hasAttribute("data-use")) { if (!t.disabled) useItem(t.getAttribute("data-use")); return; }
    if (t.hasAttribute("data-cat")) { view.category = t.getAttribute("data-cat"); render(); return; }
    if (t.hasAttribute("data-item")) {
      var id = t.getAttribute("data-item");
      view.sel = view.sel === id ? null : id;
      view.pop = null; note("");
      render();
      return;
    }
    if (t.hasAttribute("data-slot")) {
      var bucket = t.getAttribute("data-slot"), ring = t.getAttribute("data-ring") || "";
      var picked = view.sel ? findOwned(view.sel) : null;
      if (picked && accepts(picked, bucket)) { equipTo(bucket, picked.equip.id, ring || undefined); return; }
      var wasOpen = view.pop && view.pop.bucket === bucket && (view.pop.ring || "") === ring;
      var rect = t.getBoundingClientRect();
      view.pop = wasOpen ? null : { bucket: bucket, ring: ring, anchor: { left: rect.left, top: rect.top, bottom: rect.bottom, width: rect.width } };
      view.sel = null; note("");
      render();
      return;
    }
    if (t.hasAttribute("data-pop-id")) { equipTo(view.pop.bucket, t.getAttribute("data-pop-id"), view.pop.ring || undefined); return; }
    if (t.hasAttribute("data-pop-shield")) { equipTo("shield"); return; }
    if (t.hasAttribute("data-attune")) { attuneViaDossier(t.getAttribute("data-attune")); return; }
    if (t.hasAttribute("data-equip-sel")) {
      var r = findOwned(view.sel);
      if (r && r.equip) equipTo(r.equip.slot, r.equip.id, r.equip.slot === "ring" ? ringTarget(r.equip.id) : undefined);
      return;
    }
    if (t.hasAttribute("data-swap-sidearm")) {
      window.EquipmentEngine.swapSidearm();
      view.pop = null;
      render();
    }
  }

  function onDblClick(ev) {
    var t = ev.target && ev.target.closest ? ev.target.closest("[data-item]") : null;
    if (t) quickAct(t.getAttribute("data-item"));
  }

  function open() {
    build();
    if (dlg.open) return;
    view.category = ""; view.sel = null; view.drag = null; view.pop = null; view.note = "";
    render();
    if (!dlg.showModal) { window.alert("This browser is too old to show the Inventory."); return; }
    dlg.showModal();
    placePop();
  }

  function close() { if (dlg && dlg.open) dlg.close(); }
  function toggle() { if (dlg && dlg.open) close(); else open(); }

  INV.open = open;
  INV.close = close;
  INV.toggle = toggle;

  /* --------------------------------------------------------------- global keys */

  function isTextTarget(t) {
    if (!t || !t.tagName) return false;
    var tag = t.tagName.toLowerCase();
    return tag === "textarea" || tag === "select" || t.isContentEditable ||
      (tag === "input" && /^(text|search|number|email|password|url|tel)$/i.test(t.type || "text"));
  }

  document.addEventListener("keydown", function (ev) {
    if (ev.ctrlKey || ev.metaKey || ev.altKey) return;
    if (dlg && dlg.open) return; // the dialog's own listener handles I while it's open
    if (isTextTarget(ev.target)) return;
    if (document.querySelector("dialog[open]")) return; // another dialog (save/load, lorebook) is up
    if (ev.key === "i" || ev.key === "I") {
      ev.preventDefault();
      open();
    }
  });
})();
