nav = new SceneNavigator([
 "startup",
 "camp_night",
 "dawn_trial",
 "battle_black_sinks",
 "alderford"
]);
stats = {
 "choice_title": "A Mercenary's Path",
 "implicit_control_flow": "true",
 "mature_content": "true",
 "show_stat_hints": "true",
 "name": "Corin",
 "race": "human",
 "race_title": "Human",
 "race_desc": "Common human stock. Unremarkable to look at, adaptable enough to thrive in any gutter, court, or killing field.",
 "race_darkvision": "false",
 "race_trait_title": "Versatile",
 "race_trait_desc": "No single edge, but no glaring gap either.",
 "race_cantrip": "none",
 "race_cantrip_desc": "You know no innate magic.",
 "race_cantrip_2": "none",
 "race_cantrip_2_desc": "You know no second innate working.",
 "warlock_cantrip": "none",
 "warlock_cantrip_desc": "You have called on no power yet.",
 "warlock_cantrip_2": "none",
 "warlock_cantrip_2_desc": "You have called on no second power yet.",
 "warlock_spell": "none",
 "warlock_spell_desc": "You have bound no true spell to your pact yet.",
 "warlock_spell_slots": "1",
 "wizard_cantrip": "none",
 "wizard_cantrip_desc": "You have mastered no working yet.",
 "wizard_cantrip_2": "none",
 "wizard_cantrip_2_desc": "You have mastered no second working yet.",
 "wizard_cantrip_3": "none",
 "wizard_cantrip_3_desc": "You have mastered no third working yet.",
 "wizard_spell": "none",
 "wizard_spell_desc": "Your spellbook holds nothing yet.",
 "wizard_spell_slots": "2",
 "bard_cantrip": "none",
 "bard_cantrip_desc": "You have no trick ready yet.",
 "bard_cantrip_2": "none",
 "bard_cantrip_2_desc": "You have no second trick ready yet.",
 "bard_spell": "none",
 "bard_spell_desc": "You have no verse bound to magic yet.",
 "bard_spell_2": "none",
 "bard_spell_2_desc": "You have no second verse bound to magic yet.",
 "bard_spell_slots": "2",
 "gender": "man",
 "age": "19",
 "age_desc": "Nineteen winters (A green youth)",
 "origin": "runaway",
 "origin_title": "Fugitive",
 "origin_desc": "A desperate runaway fleeing debts and the noose.",
 "build": "broad",
 "build_desc": "Broad-shouldered and heavy-set",
 "hair_eyes": "Shaved scalp, flint-grey eyes",
 "mark": "Crooked nose and a split brow",
 "family_tie": "none",
 "family_name": "None",
 "family_title": "Last of Your Line",
 "family_desc": "Untethered; no surviving kin or ties left behind.",
 "weapon": "falchion",
 "weapon_desc": "Heavy falchion & iron buckler",
 "weapon_damage": "1d8 slashing",
 "weapon_type": "melee",
 "weapon_hands": "one_handed",
 "has_shield": "true",
 "shield_equipped": "true",
 "armor": "brigandine",
 "armor_desc": "Padded gambeson & leather brigandine",
 "armor_type": "brigandine",
 "starting_weapon": "falchion",
 "starting_weapon_desc": "Heavy falchion & iron buckler",
 "starting_weapon_damage": "1d8 slashing",
 "starting_weapon_type": "melee",
 "starting_weapon_hands": "one_handed",
 "equipped_weapon_id": "starting",
 "loadout_initialized": "false",
 "max_attunement_slots": "5",
 "attuned_count": "0",
 "hearthstone_attuned": "false",
 "character_class": "none",
 "class_title": "Unproven Recruit",
 "class_name": "Recruit",
 "class_assigned": "false",
 "hit_die_max": "10",
 "class_feature_title": "None",
 "class_feature_desc": "You have not yet manifested a defining class feature.",
 "class_feature_2_title": "None",
 "class_feature_2_desc": "You have no second defining class feature.",
 "fighter_fighting_style": "none",
 "fighter_second_wind_uses": "1",
 "second_wind_roll": "0",
 "rogue_expertise_1": "none",
 "rogue_expertise_2": "none",
 "rogue_sneak_attack_die": "1d6",
 "ranger_favored_enemy": "none",
 "ranger_favored_terrain": "none",
 "barbarian_rage_uses": "2",
 "barbarian_rage_damage_bonus": "2",
 "is_raging": "false",
 "warlock_patron": "none",
 "warlock_patron_title": "None",
 "warlock_patron_desc": "You have made no pact with anything.",
 "calendar_date": "14th of Scorpio, 428 IR",
 "calendar_month": "Scorpio",
 "calendar_month_num": "8",
 "calendar_day": "14",
 "calendar_year": "428",
 "campaign_day": "1",
 "current_season": "Autumn",
 "minutes_to_pass": "0",
 "hours_to_pass": "0",
 "days_to_pass": "0",
 "days_to_pay": "16",
 "day_suffix": "th",
 "clock_hour": "19",
 "clock_minute": "0",
 "clock_time": "19:00",
 "time_period": "Evening",
 "physical_state": "Shivering in damp wool; exploring camp",
 "character_level": "1",
 "hit_die": "1d10",
 "prof_bonus": "2",
 "hp_current": "12",
 "hp_max": "12",
 "armor_class": "13",
 "strength": "10",
 "dexterity": "10",
 "constitution": "10",
 "intelligence": "10",
 "wisdom": "10",
 "charisma": "10",
 "base_constitution": "10",
 "str_mod": "0",
 "dex_mod": "0",
 "con_mod": "0",
 "int_mod": "0",
 "wis_mod": "0",
 "cha_mod": "0",
 "str_mod_str": "+0",
 "dex_mod_str": "+0",
 "con_mod_str": "+0",
 "int_mod_str": "+0",
 "wis_mod_str": "+0",
 "cha_mod_str": "+0",
 "ruthless": "50",
 "silver": "12",
 "copper": "0",
 "gold": "0",
 "lyra_bond": "0",
 "varren_respect": "0",
 "vane_standing": "0",
 "kestrel_respect": "0",
 "ysolde_respect": "0",
 "odessa_respect": "0",
 "torvald_respect": "0",
 "rorik_regard": "0",
 "janna_regard": "0",
 "talia_regard": "0",
 "intake_completed": "false",
 "met_varren": "false",
 "met_lyra": "false",
 "met_vane": "false",
 "met_kestrel": "false",
 "met_ysolde": "false",
 "met_odessa": "false",
 "met_rorik": "false",
 "met_torvald": "false",
 "met_janna": "false",
 "met_talia": "false",
 "squad": "none",
 "squad_title": "None",
 "d20_roll": "10",
 "d20_roll_2": "10",
 "check_stat": "cha",
 "check_dc": "10",
 "check_skill": "Persuasion",
 "check_mod": "0",
 "check_total": "10",
 "check_success": "true",
 "is_nat_20": "false",
 "is_nat_1": "false",
 "advantage": "false",
 "disadvantage": "false",
 "guidance_active": "false",
 "save_vs": "none",
 "meal_buff_active": "false",
 "meal_buff_name": "none",
 "meal_buff_desc": "none",
 "meal_buff_stat": "none",
 "meal_buff_bonus": "0",
 "meal_buff_minutes_left": "0",
 "taphouse_dice_bankroll": "200",
 "roll_locked": "false",
 "locked_page_id": "0",
 "locked_guidance_roll": "0",
 "locked_adv_label": "",
 "roll_had_advantage": "false",
 "damage_roll_locked": "false",
 "locked_damage_page_id": "0",
 "combat_player_hit_locked": "false",
 "locked_combat_player_hit_page_id": "0",
 "combat_enemy_atk_locked": "false",
 "locked_combat_enemy_atk_page_id": "0",
 "combat_magic_missile_locked": "false",
 "locked_combat_magic_missile_page_id": "0",
 "second_wind_locked": "false",
 "locked_second_wind_page_id": "0",
 "activate_rage_locked": "false",
 "locked_activate_rage_page_id": "0",
 "combat_enemy_name": "none",
 "combat_enemy_hp": "0",
 "combat_enemy_max_hp": "0",
 "combat_enemy_ac": "10",
 "combat_enemy_atk_bonus": "0",
 "combat_enemy_dmg_dice_sides": "4",
 "combat_enemy_dmg_bonus": "0",
 "combat_enemy_disadvantage": "false",
 "combat_enemy_advantage": "false",
 "combat_enemy_atk_total": "0",
 "combat_enemy_hit_success": "false",
 "combat_enemy_dmg_dealt": "0",
 "combat_player_dmg_dice_sides": "4",
 "combat_player_dmg_bonus": "0",
 "combat_player_dmg_dealt": "0",
 "combat_weapon_hit_locked": "false",
 "locked_combat_weapon_hit_page_id": "0",
 "combat_sneak_attack_triggered": "false",
 "has_attack_cantrip": "false",
 "attack_cantrip_name": "",
 "attack_cantrip_stat": "int",
 "attack_cantrip_dice_sides": "6",
 "combat_round": "0",
 "combat_outcome": "",
 "combat_enemy_count": "1",
 "combat_active_target": "1",
 "combat_all_enemies_dead": "false",
 "combat_enemy1_name": "none",
 "combat_enemy1_hp": "0",
 "combat_enemy1_max_hp": "0",
 "combat_enemy1_ac": "10",
 "combat_enemy1_atk_bonus": "0",
 "combat_enemy1_dmg_dice_sides": "4",
 "combat_enemy1_dmg_bonus": "0",
 "combat_enemy1_epithet": "the creature",
 "combat_enemy2_name": "none",
 "combat_enemy2_hp": "0",
 "combat_enemy2_max_hp": "0",
 "combat_enemy2_ac": "10",
 "combat_enemy2_atk_bonus": "0",
 "combat_enemy2_dmg_dice_sides": "4",
 "combat_enemy2_dmg_bonus": "0",
 "combat_enemy2_epithet": "the second creature",
 "combat_flavor_enemy2_hit": "",
 "combat_flavor_enemy2_miss": "",
 "combat_enemy3_name": "none",
 "combat_enemy3_hp": "0",
 "combat_enemy3_max_hp": "0",
 "combat_enemy3_ac": "10",
 "combat_enemy3_atk_bonus": "0",
 "combat_enemy3_dmg_dice_sides": "4",
 "combat_enemy3_dmg_bonus": "0",
 "combat_enemy3_epithet": "the third creature",
 "combat_flavor_enemy3_hit": "",
 "combat_flavor_enemy3_miss": "",
 "combat_enemy_epithet": "the creature",
 "combat_flavor_weapon_hit": "",
 "combat_flavor_weapon_miss": "",
 "combat_flavor_cantrip_hit": "",
 "combat_flavor_cantrip_miss": "",
 "combat_flavor_enemy_hit": "",
 "combat_flavor_enemy_miss": "",
 "combat_flavor_dissonant_hit": "",
 "combat_flavor_dissonant_miss": "",
 "shield_armed": "false",
 "combat_shield_triggered": "false",
 "hex_active": "false",
 "hexblood_hex_used": "false",
 "temp_hp": "0",
 "agathys_active": "false",
 "combat_agathys_triggered": "false",
 "combat_agathys_shattered": "false",
 "combat_cast_locked": "false",
 "locked_combat_cast_page_id": "0",
 "combat_cast_result": "0",
 "combat_dissonant_whispers_locked": "false",
 "locked_combat_dissonant_whispers_page_id": "0",
 "currency_txn_locked": "false",
 "locked_currency_txn_page_id": "0",
 "stat_bump_locked": "false",
 "locked_stat_bump_page_id": "0",
 "locked_heal_roll": "0",
 "stat_bump2_locked": "false",
 "locked_stat_bump2_page_id": "0",
 "currency_add_amount": "0",
 "wager_bankroll_var": "taphouse_dice_bankroll",
 "wager_ante_copper": "0",
 "wager_win_copper": "0",
 "wager_bankroll_busted": "false",
 "wager_ante_locked": "false",
 "locked_wager_ante_page_id": "0",
 "wager_win_locked": "false",
 "locked_wager_win_page_id": "0",
 "tavern_item_cost_copper": "0",
 "tavern_item_hp_heal": "0",
 "tavern_item_buff_name": "",
 "tavern_item_buff_desc": "",
 "tavern_item_buff_stat": "",
 "tavern_item_buff_bonus": "0",
 "tavern_item_buff_minutes": "0",
 "tavern_purchase_locked": "false",
 "locked_tavern_purchase_page_id": "0",
 "time_advance_locked": "false",
 "locked_time_advance_page_id": "0",
 "locked_time_advance_id": "",
 "time_advance_call_id": "",
 "camp_activity": "none",
 "camp_actions_left": "4",
 "visited_lyra": "false",
 "visited_dice": "false",
 "visited_varren": "false",
 "visited_whetstone": "false",
 "visited_sentry": "false",
 "visited_odessa_night": "false",
 "visited_mess": "false",
 "battle_ready": "false",
 "prep_honed_blade": "false",
 "prep_marsh_intel": "false",
 "prep_odessa_salve": "false",
 "prep_lyra_pact": "false",
 "prep_varren_drill": "false",
 "knows_torvald_sluice_trick": "false",
 "knows_highland_striking_cadence": "false",
 "bivouac_actions_left": "3",
 "visited_bivouac_companion": "false",
 "visited_bivouac_lyra": "false",
 "visited_bivouac_kestrel": "false",
 "visited_bivouac_ysolde": "false",
 "visited_bivouac_search": "false",
 "visited_bivouac_fire": "false",
 "visited_bivouac_odessa": "false",
 "errand_kestrel_unlocked": "false",
 "errand_ysolde_unlocked": "false",
 "errand_vanguard_unlocked": "false",
 "intel_fish_cache": "false",
 "found_fish_cache": "false",
 "found_customs_vellum": "false",
 "codex_gilded_scales": "false",
 "codex_black_oath": "false",
 "codex_baron_karr": "false",
 "codex_ashbrook": "false",
 "codex_karrs_keep": "false",
 "codex_port_valen": "false",
 "codex_black_sinks": "false",
 "codex_the_drowned": "false",
 "codex_meridian_empire": "false",
 "codex_odessa": "false",
 "codex_broken_crags": "false",
 "codex_iron_bailiffs": "false",
 "codex_marsh_squatters": "false",
 "codex_alderford": "false",
 "visited_alder_weavers": "false",
 "visited_talia_loft": "false",
 "talia_invitation_open": "false",
 "visited_alder_cadre": "false",
 "visited_alder_smithy": "false",
 "visited_alder_tavern": "false",
 "discussed_lyra_valen": "false",
 "discussed_lyra_archery": "false",
 "discussed_lyra_pay": "false",
 "discussed_lyra_pact": "false",
 "asked_rorik_alderford": "false",
 "discussed_smiths_past": "false",
 "bought_smiths_ale": "false",
 "discussed_alderford_life": "false",
 "visited_maura_cellar": "false",
 "maura_cellar_cleared": "false",
 "culvert_bounty_silver": "4",
 "met_maura": "false",
 "met_rennick": "false",
 "discussed_maura_past": "false",
 "discussed_river_conditions": "false",
 "visited_lyra_taphouse": "false",
 "visited_smiths_table": "false",
 "janna_romanced": "false",
 "bard_performed_taphouse": "false",
 "has_free_taphouse_drink": "false",
 "won_rorik_dice": "false",
 "lyra_pay_generous": "false",
 "visited_alder_guild": "false",
 "visited_alder_bathhouse": "false",
 "alder_actions_left": "3",
 "turned_in_customs_vellum": "false",
 "studied_customs_vellum": "false",
 "alder_river_chain_cleared": "false",
 "elspeth_safe": "false",
 "elspeth_with_company": "false",
 "elspeth_role": "none",
 "elspeth_bond": "55",
 "weaver_gratitude": "false",
 "gilded_scales_leverage": "false",
 "alder_wager_won": "false",
 "prep_waterproof_gear": "false",
 "has_hearthstone_talisman": "false",
 "has_timber_axe": "false",
 "has_stiletto": "false",
 "has_iron_crowbar": "false",
 "has_talia_provisions": "false",
 "intimate_encounters": "0"
};
purchases = {};
achievements = [];
nav.setStartingStatsClone(stats);if (achievements.length) {
  nav.loadAchievements(achievements);
}
if (nav.loadProducts) nav.loadProducts([], purchases);

isCogPublished = true;

