nav = new SceneNavigator([
 "startup",
 "camp_night"
]);
stats = {
 "choice_title": "A Mercenary's Path",
 "implicit_control_flow": "true",
 "mature_content": "true",
 "show_stat_hints": "true",
 "name": "Corin",
 "gender": "man",
 "age": "19",
 "age_desc": "Nineteen winters (A green youth)",
 "origin": "runaway",
 "origin_title": "Fugitive",
 "origin_desc": "A desperate runaway fleeing debts and the noose.",
 "build": "broad",
 "build_desc": "Broad-shouldered and heavy-set",
 "hair_eyes": "Shaved scalp, cold flint-grey eyes",
 "mark": "Crooked nose and a split brow",
 "family_tie": "none",
 "family_name": "None",
 "family_title": "Last of Your Line",
 "family_desc": "Untethered; no surviving kin or ties left behind.",
 "weapon": "falchion",
 "weapon_desc": "Heavy falchion & iron buckler",
 "weapon_damage": "1d8 slashing",
 "weapon_type": "melee",
 "has_shield": "true",
 "armor": "brigandine",
 "armor_desc": "Padded gambeson & leather brigandine",
 "armor_type": "brigandine",
 "calendar_date": "14th of Scorpio, 428 IR",
 "calendar_month": "Scorpio",
 "calendar_day": "14",
 "calendar_year": "428",
 "campaign_day": "1",
 "current_season": "Autumn",
 "clock_hour": "21",
 "clock_minute": "0",
 "clock_time": "21:00",
 "time_period": "Late Night",
 "physical_state": "Shivering in damp wool; exploring camp",
 "character_level": "1",
 "hit_die": "1d10",
 "prof_bonus": "2",
 "hp_current": "12",
 "hp_max": "12",
 "armor_class": "13",
 "strength": "10",
 "dexterity": "10",
 "constitution": "10",
 "intelligence": "10",
 "wisdom": "10",
 "charisma": "10",
 "str_mod": "0",
 "dex_mod": "0",
 "con_mod": "0",
 "int_mod": "0",
 "wis_mod": "0",
 "cha_mod": "0",
 "str_mod_str": "+0",
 "dex_mod_str": "+0",
 "con_mod_str": "+0",
 "int_mod_str": "+0",
 "wis_mod_str": "+0",
 "cha_mod_str": "+0",
 "ruthless": "50",
 "silver": "12",
 "lyra_bond": "0",
 "varren_respect": "0",
 "vane_standing": "0",
 "intake_completed": "false",
 "met_varren": "false",
 "met_lyra": "false",
 "met_vane": "false",
 "d20_roll": "10",
 "check_stat": "cha",
 "check_dc": "10",
 "check_skill": "Persuasion",
 "check_mod": "0",
 "check_total": "10",
 "check_success": "true",
 "is_nat_20": "false",
 "is_nat_1": "false",
 "camp_activity": "none",
 "camp_actions_left": "2",
 "visited_lyra": "false",
 "visited_dice": "false",
 "visited_varren": "false",
 "battle_ready": "false",
 "codex_carrion": "true",
 "codex_vane": "true",
 "codex_varren": "true",
 "codex_lyra": "true",
 "codex_gilded_scales": "false",
 "codex_black_tally": "false",
 "codex_baron_karr": "false",
 "codex_ashbrook": "false",
 "codex_karrs_keep": "false",
 "codex_port_valen": "false",
 "codex_black_sinks": "false"
};
purchases = {};
achievements = [];
nav.setStartingStatsClone(stats);if (achievements.length) {
  nav.loadAchievements(achievements);
}
if (nav.loadProducts) nav.loadProducts([], purchases);

isCogPublished = true;

